program-analysis/echidna/README.md
program-analysis/echidna/scripts/gh_action_test.sh

This small PR will update the Echidna version to use v1.6.0 in the tutorials as well as in the CI tests.

Update Echidna to 1.6.0

---

program-analysis/echidna/README.md
program-analysis/echidna/assertion-checking.md

This PR added an example on the use of events for assertion checking (available in Echidna 1.6.0) as well as some general fixes in the rest of the tutorial.

Improved assertion checking tutorial

---

program-analysis/echidna/example/blacklistpushpop.yaml
program-analysis/echidna/example/filter.yaml
program-analysis/echidna/filtering-functions.md
program-analysis/echidna/finding-transactions-with-high-gas-consumption.md
program-analysis/echidna/scripts/gh_action_test.sh

This PR updates Echidna to the release 1.6.1, updating the function filter tutorial and examples. Manticore tests are failing, but they should be fixed in a different PR.

Update to Echidna 1.6.1

---

program-analysis/echidna/end-to-end-testing.md

This tutorial presents a new approach to use Echidna called end-to-end testing (a.k.a. E2E). It uses a simple truffle box called drizzle, which is absolutely basic in terms of code, since metacoin required to know exactly how libraries are deployed and there is still a gap for that in our tooling. It it worth mentioning that this is the first iteration and the required branches and the UI will improve in the near future.

Tutorial on end-to-end testing with Echidna

---

program-analysis/echidna/testing-bytecode.md

In the `testing-bytecode` example, the code does not compile with the recommended version of solc (0.5.11). Also, the first Echidna call doesn't specify the contract so Echidna will not run as expected.

Fixes for Solidity 0.5.11 / omission of a contract name in a test

---

README.md
learn_evm/README.md
learn_evm/eips_forks.md

This PR adds a new section: learn EVM. For now the only section is a table summarizing the EIPs associated with every fork. Other sections will be added later (ex: https://github.com/crytic/building-secure-contracts/issues/75).

Add learn EVM section with the list of EIPs<>Forks

---

.github/workflows/ci.yml

By disabling fail-fast, all three jobs are run completely, instead of
being cancelled mid-execution if one of them fails.

Disable fail-fast on GH Actions matrix

---

program-analysis/manticore/scripts/gh_action_test.sh

The code has not been adapted to the newer Manticore and crytic-compile releases yet,
so this pins the dependencies to the last working versions until the
tests can be updated.

Fix manticore tests in CI

---

.github/workflows/echidna.yml

This PR introduces a new Actions workflow that leverages the Echidna action to run the tests.
Apart from providing a good test case for the Echidna action, this should enhance visibility into the passing state of the different test cases, as well as allow for ignoring flaky tests temporarily (`flaky: true`). Adding future tests should also become slightly easier.

Use Echidna action for CI tests

---

development-guidelines/README.md
development-guidelines/incident_response.md

We have the token integration checklist that we add to reports, while linking to building-secure-contracts for the most up-to-date version.
I'd like to do the same thing for the incident response plan recommendations that we're providing clients as well. This helps with uniformity – and also makes sure we can add/update our guidance.

Added incident response recommendations

---

not-so-smart-contracts/cairo/README.md
not-so-smart-contracts/cairo/access_controls/README.md
not-so-smart-contracts/cairo/arithmetic_overflow/README.md
not-so-smart-contracts/cairo/integer_division/README.md
not-so-smart-contracts/cairo/replay_protection/README.md
not-so-smart-contracts/cairo/view_state/README.md

Adds some initial examples for Cairo in the style of [Not-So-Smart-Contracts](https://github.com/crytic/not-so-smart-contracts).

Add not-so-smart-contracts/cairo

---

program-analysis/echidna/end-to-end-testing.md

This is a minor PR to update the documentation for `end-to-end-testing.md` so that it highlights the latest changes to Etheno.

Update E2E documentation

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/echidna.yml

Ubuntu 18.04 is getting sunset soon in GitHub Actions, so this PR upgrades to 22.04, and also adds dependabot to keep GitHub Actions up to date.

Upgrade CI Ubuntu

---

program-analysis/echidna/common-testing-approaches.md
program-analysis/echidna/testing-modes.md

* fix: adding toc to testing modes md
* fix: adding toc for the common testing approaches md

[Docs]: Adding TOC for two README docs

---

development-guidelines/guidelines.md

Adds general guidance regarding delegatecall proxies & how to avoid related footguns

init delegatecall guidelines

---

program-analysis/echidna/property-creation.md

Some code samples refer to the ERC20 token as `t` and in other instances as `token`; this inconsistency may cause confusion.
Suggestion: use `token`

Inconsistency in `token` variable naming

---

not-so-smart-contracts/cairo/incorrect_felt_comparison/README.md

Fixes incorrect comparison operators in the description for `assert_le` and `assert_nn_le``.
Additionally:
- Improve the formatting and minor edits
- Update Cairo syntax to 0.10.0

fix: incorrect comparison operator

---

resources/tob_blogposts.md

Based on https://github.com/crytic/building-secure-contracts/pull/152 + some improvements

tob blogposts list

---

.github/workflows/echidna.yml
program-analysis/echidna/Exercise-7.md
program-analysis/echidna/exercises/exercise7/config.yaml
program-analysis/echidna/exercises/exercise7/solution.sol

Removes the need for Etheno in Exercise 7

Make echidna exercise-7 solution self contained

---

program-analysis/manticore/running-under-manticore.md

The naming change from "API" to "EVM" seems to have broken some links in the documentation. 
This PR fixes those links.

docs: fix broken links

---

program-analysis/echidna/Exercise-5.md

My biggest struggle with this level was passing the `echidna-test: Deploying the contract 0x00a329c0648769A73afAc7F9381E08FB43dBEA72 failed (revert, out-of-gas, sending ether to an non-payable constructor, etc.)` error. 
It is caused by not passing the initial Ether to the test contract via `balanceContract` in the config file. 
This is pretty obvious to me now, but I think I either missed it while reviewing the materials, or it wasn't showcased.
This PR:
- adds a small hint that will guide the person to explore the available config options on their own and does not spoil the solution

Solving the level is not possible without knowing the available config options

---

program-analysis/echidna/README.md

This PR fixes the names of exercises 5 and 6.
The names were already fixed in #148 but were overridden by accident in #143.
With this PR, they will return to the state from #148.

Exercise 5 and 6 names were swapped

---

program-analysis/echidna/end-to-end-testing.md

I couldn't get Etheno to work with Ganache installed on the project level. 
It works when installed globally. 
This PR:
- adds appropriate flags to Ganache installation commands to make it available globally
As I am not sure if it is a good practice to install npm packages globally, feedback would be appreciated ✌🏼
Thanks!

Install Ganache globally

---

.github/workflows/echidna.yml

There's an issue parsing Hardhat projects in the `edge` containers at this time, due to crytic/crytic-compile#364. This change should be reverted once a new crytic-compile release is produced.

ci: echidna: temporarily use latest stable version

---

program-analysis/echidna/assertion-checking.md

This PR:
- fixes a small typo in the word "work".

docs: typo fix

---

program-analysis/manticore/adding-constraints.md

There is no `exercises.md` file, only the `exercises` folder.

docs: fix broken link

---

program-analysis/echidna/Exercise-1.md
program-analysis/echidna/Exercise-2.md
program-analysis/echidna/Exercise-3.md
program-analysis/echidna/Exercise-4.md
program-analysis/echidna/Exercise-7.md
program-analysis/echidna/Exercise-8.md
program-analysis/echidna/frequently_asked_questions.md
program-analysis/echidna/fuzzing_tips.md
program-analysis/echidna/property-creation.md
program-analysis/echidna/testing-bytecode.md

Fixes #200 
Echidna exercise 8 has no hint in the `damn-vulnerable-defi-echidna` repo, will update the link when it's fixed (so far will be broken)

Fix broken links in Echidna markdown files

---

program-analysis/echidna/property-creation.md

Isn't the boundary `val = val % token.balanceOf(address(this))` missing the maximal value of `token.balanceOf(address(this))`?
In the [Learn how to fuzz like a pro: Intro to AMM's invariants](https://youtu.be/n0RaKKVTGvA?t=4738), Justin creates a helper function to create a boundary on the `amount`. 
It looks like this:
```solidity
function _between(
uint256 amount,
uint256 low,
uint256 high
) internal pure returns (uint256) {
return (low + (amount % (high - low + 1)));
}
```
`+1` is added to include the maximal value that can be sent. 
As explained in [this video on the modulo operator by Golan Levin](https://www.youtube.com/watch?v=r5Iy3v1co0A&t=159s), the modulo operator:
| mod | remainder |
| --- | --- |
| 5%5|0|
|6%5|1|
|7%5|2|
|8%5|3|
|9%5|4|
|10%5|0|
|11%5|1|
...
and the cycle …

docs: fix value boundary

---

program-analysis/slither/exercises/exercise1/solution.py

Current solution is checking for `mint.contract` that seems to always return the current contract.
As a result, it returns an error for any contract that inherits from `Coin`, even if it does not override `_mint`.
It also returns an error for contracts inheriting from a contract overriding `_mint` (see issue #10) even if they don't override `_mint` themselves.
Fixes #10.

Fix for Slither exercise 1

---

program-analysis/echidna/example/multiabi.yaml

Echidna renamed its `multi-abi` option to `allContracts` in commit ff312a6 ("Rename multi-abi to allContracts"). This adds the new option to the test configuration to keep CI passing, while maintaining references in text to the currently available option to not confuse users. A second PR should adjust the text to mention the new option once Echidna 2.1 is released.

echidna: replace multi-abi with allContracts in configs

---

not-so-smart-contracts/substrate/README.md

https://secure-contracts.com/not-so-smart-contracts/substrate/ currently has broken links (they go to a 404 page). This PR changes the links so they point to the directory instead of the README.md, which is how the links are done in https://secure-contracts.com/not-so-smart-contracts/solana/ etc. This should fix the broken links on the website.

Fix broken links on site

---

program-analysis/manticore/exercises/example.md
program-analysis/manticore/exercises/exercise1.md
program-analysis/manticore/exercises/exercise2.md

- fix spelling
- make headers uniform and fix ones that weren't rendering

fix spelling and formatting

---

.github/workflows/deploy.yml
.github/workflows/echidna.yml
.github/workflows/lint_links.yml
.github/workflows/manticore.yml
.github/workflows/slither.yml

Some action triggers can be further restricted. Re https://github.com/crytic/building-secure-contracts/issues/214

Constrain CI triggers

---

not-so-smart-contracts/cosmos/non_determinism/README.md

FILE: ./not-so-smart-contracts/cosmos/non_determinism/README.md [✖] https://lev.pm/posts/2020-04-18-golang-map-randomness/
Fixes #291

Fix cosmos link

---

program-analysis/manticore/symbolic-execution-introduction.md

Addressed issue https://github.com/crytic/building-secure-contracts/issues/241#issue-1615922662

Removed duplicate link in manticore blogposts

---

static/script.js

Discovered the issue, was injecting the Hubspot JS script as `additional-js`, however, the contents of the static/script.js file were HTML.  Converted contents to JS.

Fixing script

---

program-analysis/echidna/advanced/collecting-a-corpus.md

Updates the coverage examples to match the newest Echidna. I re-generated them by running Echidna.

Update coverage for Echidna 2.2.0

---

.github/workflows/lint_links.yml

This makes the action only check changed files (compared against master) on pull requests. It also schedules it to run on the whole repo on Tuesdays and pins `actions/checkout` to v3 instead of master.
Closes: #303

ci: lint_links: only check changed files on pull requests

---

learn_evm/arithmetic-checks.md

This PR
- Fixes some of the spacing in the latex graphics
- Removes some inline math that is not rendered
- Wraps `int256` in code blocks
- Changes some of the points in the conclusion
- Removes `\phantom`

Include small fixes to arithmetic checks article

---

program-analysis/echidna/exercises/exercise1/solution.sol
program-analysis/echidna/exercises/exercise1/template.sol
program-analysis/echidna/exercises/exercise2/solution.sol
program-analysis/echidna/exercises/exercise2/template.sol
program-analysis/echidna/exercises/exercise3/mintable.sol
program-analysis/echidna/exercises/exercise3/solution.sol
program-analysis/echidna/exercises/exercise3/template.sol

Since Solidity v0.7.0, the visibility for `constructor` is ignored.
Remove the `public` visibility from all the constructors in the exercices.
https://docs.soliditylang.org/en/v0.8.19/070-breaking-changes.html#functions-and-events]]
Also added thousand separator as `_` to increase code readability of number literals: fron `10000` to --> `10_000`.

refactor: remove `public` visibility from `constructor`s + add thousand separators to thousand numbers

---

program-analysis/echidna/advanced/working-with-libraries.md

This was already fixed in the latest echidna release

Removed note about delegatecall lack of coverage

---

.github/workflows/medusa.yml
program-analysis/echidna/example/medusa.json
program-analysis/echidna/exercises/exercise1/medusa.json
program-analysis/echidna/exercises/exercise2/medusa.json
program-analysis/echidna/exercises/exercise3/medusa.json
program-analysis/echidna/exercises/exercise4/medusa.json

This PR contains a first batch of initial CI tests using medusa to reproduce the examples and exercises. A few usability issues/fixes were discussed to the medusa team during the process

Add medusa tests to CI

---

program-analysis/echidna/basic/testing-modes.md

This PR adds a few details on testing mode to make sure it is clear how to change them, and which are the less frequently used ones (e.g. `overflow`).

Expanded testing modes with missing information
